### ISSUE TITLE
How should we handle versioning?

### ISSUE THREAD

**Issue by Trimakas** [NafaaBout/bytestand#10]
Just want to be clear.. Are we updating my version on Cloud9 or are we keeping Git up to date and I should push and pull from here?

**Comment by NafaaBout** [comment]
You should push and pull to and from this repository. I made you a
collaborator and once we finish the app development. I'll pass the full
repository to you.

On Thu, Oct 22, 2015 at 3:15 PM, Trimakas <notifications@github.com> wrote:

> Just want to be clear.. Are we updating my version on Cloud9 or are we
> keeping Git up to date and I should push and pull from here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NafaaBout/bytestand/issues/10>.
>



-- 
Nafaa Boutefer
Ruby On Rails freelance developer
From Jijel Algeria.

   - Hire me on Upwork <https://www.upwork.com/users/~01f6a8667aea62d3a9>.
   - See my public work on Github: https://github.com/nafaabout
   - Follow me on Twitter: https://twitter.com/nafaabout
